---
- name: Deploy and configure Docker on RHEL/CentOS Servers
  hosts: all
  become: True
  gather_facts: True

  tasks:
    - name: setup 2377 tcp firewall rule
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
        - 2377/tcp
        - 2377/udp
        - 7946/tcp
        - 7946/udp
        - 4789/udp
      notify: reload_firewalld

    - name: "Remove old installations"
      ansible.builtin.yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
        - podman
        - runc

    - name: "Install yum-utils"
      ansible.builtin.yum:
        name: yum-utils
        state: present

    - name: Download Docker-ce repo file
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/
        mode: '0644'

    - name: Install docker engine
      ansible.builtin.yum:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
      notify: start_docker

  handlers:
    - name: reload_firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

    - name: start_docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
