- name: setup 2377 tcp firewall rule
  community.general.ufw:
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    rule: allow
  with_items:
    - port: 2377
      proto: tcp
    - port: 2377
      proto: udp
    - port: 7946
      proto: tcp
    - port: 7946
      proto: udp
    - port: 4789
      proto: udp
  notify: restart_ufw

- name: "Remove old installations"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: absent

- name: "Update apt and install packages to allow apt to use repository over https"
  ansible.builtin.apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker engine
  ansible.builtin.apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
  notify: start_docker

