- name: copy join file from host to remote
  ansible.builtin.copy:
    src: ./join/join.sh
    dest: /root/join.sh
    mode: '0700'

- name: run join file on remote
  ansible.builtin.shell: /root/join.sh